-- H2(MySQL 모드)용 스키마. 원본 sql/ddl_brofcls.sql(MariaDB) 기반으로
-- 테이블 코멘트/인라인 인덱스/SET FOREIGN_KEY_CHECKS 등 H2 비호환 구문만 제거.

DROP TABLE IF EXISTS TB_TEST_CLS;
DROP TABLE IF EXISTS TB_BROF_TEST;
DROP TABLE IF EXISTS TB_FLD;
DROP TABLE IF EXISTS TB_CLS;
DROP TABLE IF EXISTS TB_TEST;
DROP TABLE IF EXISTS TB_BROF;

CREATE TABLE TB_BROF (
    BROF_CD  VARCHAR(10)  NOT NULL,
    BROF_NM  VARCHAR(100) NOT NULL,
    USE_YN   CHAR(1)      NOT NULL DEFAULT 'Y',
    REG_DT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RGTR_NO  VARCHAR(10)  NULL,
    CONSTRAINT PK_BROF PRIMARY KEY (BROF_CD)
);

CREATE TABLE TB_TEST (
    TEST_NO   VARCHAR(10)  NOT NULL,
    TEST_NM   VARCHAR(100) NOT NULL,
    TEST_YMD  CHAR(8)      NOT NULL,
    USE_YN    CHAR(1)      NOT NULL DEFAULT 'Y',
    REG_DT    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RGTR_NO   VARCHAR(10)  NULL,
    CONSTRAINT PK_TEST PRIMARY KEY (TEST_NO)
);
CREATE INDEX IDX_TEST_01 ON TB_TEST (TEST_YMD);

CREATE TABLE TB_BROF_TEST (
    BROF_CD  VARCHAR(10) NOT NULL,
    TEST_NO  VARCHAR(10) NOT NULL,
    REG_DT   DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RGTR_NO  VARCHAR(10) NULL,
    CONSTRAINT PK_BROF_TEST PRIMARY KEY (BROF_CD, TEST_NO),
    CONSTRAINT FK_BROF_TEST_01 FOREIGN KEY (BROF_CD) REFERENCES TB_BROF(BROF_CD),
    CONSTRAINT FK_BROF_TEST_02 FOREIGN KEY (TEST_NO) REFERENCES TB_TEST(TEST_NO)
);

CREATE TABLE TB_CLS (
    CLS_NO  VARCHAR(10)  NOT NULL,
    CLS_NM  VARCHAR(100) NOT NULL,
    USE_YN  CHAR(1)      NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_CLS PRIMARY KEY (CLS_NO)
);

CREATE TABLE TB_FLD (
    FLD_CD  VARCHAR(10)  NOT NULL,
    FLD_NM  VARCHAR(100) NOT NULL,
    USE_YN  CHAR(1)      NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_FLD PRIMARY KEY (FLD_CD)
);

CREATE TABLE TB_TEST_CLS (
    TEST_CLS_SN       BIGINT       NOT NULL AUTO_INCREMENT,
    BROF_CD           VARCHAR(10)  NOT NULL,
    TEST_NO           VARCHAR(10)  NOT NULL,
    CLS_NO            VARCHAR(10)  NOT NULL,
    FLD_CD            VARCHAR(10)  NULL,
    JOB_SE_CD         VARCHAR(10)  NOT NULL,
    TEST_PT_NO        VARCHAR(10)  NOT NULL,
    TEST_SCHD_RLS_YN  CHAR(1)      NOT NULL DEFAULT 'N',
    REG_DT            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RGTR_NO           VARCHAR(10)  NULL,
    MDFCN_DT          DATETIME     NULL,
    MDFR_NO           VARCHAR(10)  NULL,
    CONSTRAINT PK_TEST_CLS PRIMARY KEY (TEST_CLS_SN),
    CONSTRAINT FK_TEST_CLS_01 FOREIGN KEY (BROF_CD) REFERENCES TB_BROF(BROF_CD),
    CONSTRAINT FK_TEST_CLS_02 FOREIGN KEY (TEST_NO) REFERENCES TB_TEST(TEST_NO),
    CONSTRAINT FK_TEST_CLS_03 FOREIGN KEY (CLS_NO) REFERENCES TB_CLS(CLS_NO),
    CONSTRAINT FK_TEST_CLS_04 FOREIGN KEY (FLD_CD) REFERENCES TB_FLD(FLD_CD)
);
CREATE INDEX IDX_TEST_CLS_01 ON TB_TEST_CLS (BROF_CD, TEST_NO, CLS_NO, TEST_PT_NO);
