-- ========================================================================
-- 지사별 시행종목 조회 - 테이블 생성 (Oracle)
-- DB 테이블 설계서 v1.0 기준
-- ========================================================================

-- 1. 지사정보
CREATE TABLE BRANCH_INFO (
    BRANCH_CODE   VARCHAR2(10)  NOT NULL,
    BRANCH_NAME   VARCHAR2(100) NOT NULL,
    BRANCH_ADDR   VARCHAR2(200),
    BRANCH_TEL    VARCHAR2(20),
    USE_YN        VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    REG_DT        DATE          DEFAULT SYSDATE NOT NULL,
    REG_ID        VARCHAR2(50)  NOT NULL,
    UPD_DT        DATE          DEFAULT SYSDATE NOT NULL,
    UPD_ID        VARCHAR2(50)  NOT NULL,
    CONSTRAINT PK_BRANCH_INFO PRIMARY KEY (BRANCH_CODE)
);
CREATE UNIQUE INDEX UQ_INDEX_BRANCH_INFO_BRANCH_NAME ON BRANCH_INFO(BRANCH_NAME);

-- 2. 시험정보
CREATE TABLE EXAM_INFO (
    EXAM_ID       NUMBER(10)    NOT NULL,
    EXAM_NAME     VARCHAR2(200) NOT NULL,
    EXAM_DATE     DATE          NOT NULL,
    BRANCH_CODE   VARCHAR2(10)  NOT NULL,
    EXAM_TYPE     VARCHAR2(20),
    EXAM_DESC     VARCHAR2(500),
    USE_YN        VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    REG_DT        DATE          DEFAULT SYSDATE NOT NULL,
    REG_ID        VARCHAR2(50)  NOT NULL,
    UPD_DT        DATE          DEFAULT SYSDATE NOT NULL,
    UPD_ID        VARCHAR2(50)  NOT NULL,
    CONSTRAINT PK_EXAM_INFO PRIMARY KEY (EXAM_ID),
    CONSTRAINT FK_EXAM_INFO_BRANCH_CODE FOREIGN KEY (BRANCH_CODE)
        REFERENCES BRANCH_INFO(BRANCH_CODE)
);
CREATE UNIQUE INDEX UQ_INDEX_EXAM_INFO_EXAM_NAME ON EXAM_INFO(EXAM_NAME);
CREATE INDEX IDX_INDEX_EXAM_INFO_EXAM_DATE   ON EXAM_INFO(EXAM_DATE);
CREATE INDEX IDX_INDEX_EXAM_INFO_BRANCH_CODE ON EXAM_INFO(BRANCH_CODE);

CREATE SEQUENCE SEQ_EXAM_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 3. 종목코드
CREATE TABLE ITEM_CODE (
    ITEM_CODE   VARCHAR2(20)  NOT NULL,
    ITEM_NAME   VARCHAR2(100) NOT NULL,
    ITEM_TYPE   VARCHAR2(20),
    CERT_LEVEL  VARCHAR2(20),
    USE_YN      VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    REG_DT      DATE          DEFAULT SYSDATE NOT NULL,
    REG_ID      VARCHAR2(50)  NOT NULL,
    UPD_DT      DATE          DEFAULT SYSDATE NOT NULL,
    UPD_ID      VARCHAR2(50)  NOT NULL,
    CONSTRAINT PK_ITEM_CODE PRIMARY KEY (ITEM_CODE)
);
CREATE UNIQUE INDEX UQ_INDEX_ITEM_CODE_ITEM_NAME ON ITEM_CODE(ITEM_NAME);

-- 4. 선택분야
CREATE TABLE SELECT_FIELD (
    ITEM_CODE         VARCHAR2(20)  NOT NULL,
    SELECT_FIELD      VARCHAR2(20)  NOT NULL,
    SELECT_FIELD_NAME VARCHAR2(100) NOT NULL,
    USE_YN            VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    REG_DT            DATE          DEFAULT SYSDATE NOT NULL,
    REG_ID            VARCHAR2(50)  NOT NULL,
    UPD_DT            DATE          DEFAULT SYSDATE NOT NULL,
    UPD_ID            VARCHAR2(50)  NOT NULL,
    CONSTRAINT PK_SELECT_FIELD PRIMARY KEY (ITEM_CODE, SELECT_FIELD),
    CONSTRAINT FK_SELECT_FIELD_ITEM_CODE FOREIGN KEY (ITEM_CODE)
        REFERENCES ITEM_CODE(ITEM_CODE)
);
CREATE INDEX FK_INDEX_SELECT_FIELD_ITEM_CODE ON SELECT_FIELD(ITEM_CODE);

-- 5. 시행종목
CREATE TABLE EXAM_ITEM (
    ITEM_SEQ          NUMBER(15)   NOT NULL,
    EXAM_ID           NUMBER(10)   NOT NULL,
    BRANCH_CODE       VARCHAR2(10) NOT NULL,
    EXAM_DATE         DATE         NOT NULL,
    ITEM_CODE         VARCHAR2(20) NOT NULL,
    SELECT_FIELD      VARCHAR2(20),
    WORK_TYPE         VARCHAR2(20),
    PART              VARCHAR2(10),
    EXPOSE_YN         VARCHAR2(1)  DEFAULT 'N' NOT NULL,
    MAX_CANDINATE     NUMBER(10),
    CURRENT_CANDINATE NUMBER(10)   DEFAULT 0 NOT NULL,
    STATUS            VARCHAR2(20) DEFAULT 'READY' NOT NULL,
    REG_DT            DATE         DEFAULT SYSDATE NOT NULL,
    REG_ID            VARCHAR2(50) NOT NULL,
    UPD_DT            DATE         DEFAULT SYSDATE NOT NULL,
    UPD_ID            VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_EXAM_ITEM PRIMARY KEY (ITEM_SEQ),
    CONSTRAINT FK_EXAM_ITEM_EXAM_ID     FOREIGN KEY (EXAM_ID)
        REFERENCES EXAM_INFO(EXAM_ID),
    CONSTRAINT FK_EXAM_ITEM_BRANCH_CODE FOREIGN KEY (BRANCH_CODE)
        REFERENCES BRANCH_INFO(BRANCH_CODE),
    CONSTRAINT FK_EXAM_ITEM_ITEM_CODE   FOREIGN KEY (ITEM_CODE)
        REFERENCES ITEM_CODE(ITEM_CODE),
    CONSTRAINT FK_EXAM_ITEM_SELECT_FIELD FOREIGN KEY (ITEM_CODE, SELECT_FIELD)
        REFERENCES SELECT_FIELD(ITEM_CODE, SELECT_FIELD)
);
CREATE INDEX IDX_INDEX_EXAM_ITEM_EXAM_ID     ON EXAM_ITEM(EXAM_ID);
CREATE INDEX IDX_INDEX_EXAM_ITEM_BRANCH_CODE ON EXAM_ITEM(BRANCH_CODE);
CREATE INDEX IDX_INDEX_EXAM_ITEM_EXAM_DATE   ON EXAM_ITEM(EXAM_DATE);
CREATE INDEX IDX_INDEX_EXAM_ITEM_ITEM_CODE   ON EXAM_ITEM(ITEM_CODE);
CREATE INDEX IDX_INDEX_EXAM_ITEM_COMPOSITE   ON EXAM_ITEM(ITEM_CODE, PART);

CREATE SEQUENCE SEQ_EXAM_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
