-- ========================================================================
-- 지사별 시행종목 조회 - 테이블 생성 (H2 Oracle 호환 모드)
-- 로컬 개발/테스트 용도
-- ========================================================================

DROP TABLE IF EXISTS EXAM_ITEM;
DROP TABLE IF EXISTS SELECT_FIELD;
DROP TABLE IF EXISTS ITEM_CODE;
DROP TABLE IF EXISTS EXAM_INFO;
DROP TABLE IF EXISTS BRANCH_INFO;

CREATE TABLE BRANCH_INFO (
    BRANCH_CODE   VARCHAR2(10)  NOT NULL,
    BRANCH_NAME   VARCHAR2(100) NOT NULL,
    BRANCH_ADDR   VARCHAR2(200),
    BRANCH_TEL    VARCHAR2(20),
    USE_YN        VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    REG_DT        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    REG_ID        VARCHAR2(50)  NOT NULL,
    UPD_DT        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPD_ID        VARCHAR2(50)  NOT NULL,
    CONSTRAINT PK_BRANCH_INFO PRIMARY KEY (BRANCH_CODE)
);

CREATE TABLE EXAM_INFO (
    EXAM_ID       NUMBER(10)    NOT NULL,
    EXAM_NAME     VARCHAR2(200) NOT NULL,
    EXAM_DATE     DATE          NOT NULL,
    BRANCH_CODE   VARCHAR2(10)  NOT NULL,
    EXAM_TYPE     VARCHAR2(20),
    EXAM_DESC     VARCHAR2(500),
    USE_YN        VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    REG_DT        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    REG_ID        VARCHAR2(50)  NOT NULL,
    UPD_DT        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPD_ID        VARCHAR2(50)  NOT NULL,
    CONSTRAINT PK_EXAM_INFO PRIMARY KEY (EXAM_ID),
    CONSTRAINT FK_EXAM_INFO_BRANCH_CODE FOREIGN KEY (BRANCH_CODE)
        REFERENCES BRANCH_INFO(BRANCH_CODE)
);

CREATE TABLE ITEM_CODE (
    ITEM_CODE   VARCHAR2(20)  NOT NULL,
    ITEM_NAME   VARCHAR2(100) NOT NULL,
    ITEM_TYPE   VARCHAR2(20),
    CERT_LEVEL  VARCHAR2(20),
    USE_YN      VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    REG_DT      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    REG_ID      VARCHAR2(50)  NOT NULL,
    UPD_DT      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPD_ID      VARCHAR2(50)  NOT NULL,
    CONSTRAINT PK_ITEM_CODE PRIMARY KEY (ITEM_CODE)
);

CREATE TABLE SELECT_FIELD (
    ITEM_CODE         VARCHAR2(20)  NOT NULL,
    SELECT_FIELD      VARCHAR2(20)  NOT NULL,
    SELECT_FIELD_NAME VARCHAR2(100) NOT NULL,
    USE_YN            VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    REG_DT            TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    REG_ID            VARCHAR2(50)  NOT NULL,
    UPD_DT            TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPD_ID            VARCHAR2(50)  NOT NULL,
    CONSTRAINT PK_SELECT_FIELD PRIMARY KEY (ITEM_CODE, SELECT_FIELD),
    CONSTRAINT FK_SELECT_FIELD_ITEM_CODE FOREIGN KEY (ITEM_CODE)
        REFERENCES ITEM_CODE(ITEM_CODE)
);

CREATE TABLE EXAM_ITEM (
    ITEM_SEQ          NUMBER(15)   NOT NULL,
    EXAM_ID           NUMBER(10)   NOT NULL,
    BRANCH_CODE       VARCHAR2(10) NOT NULL,
    EXAM_DATE         DATE         NOT NULL,
    ITEM_CODE         VARCHAR2(20) NOT NULL,
    SELECT_FIELD      VARCHAR2(20),
    WORK_TYPE         VARCHAR2(20),
    PART              VARCHAR2(10),
    EXPOSE_YN         VARCHAR2(1)  DEFAULT 'N' NOT NULL,
    MAX_CANDINATE     NUMBER(10),
    CURRENT_CANDINATE NUMBER(10)   DEFAULT 0 NOT NULL,
    STATUS            VARCHAR2(20) DEFAULT 'READY' NOT NULL,
    REG_DT            TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    REG_ID            VARCHAR2(50) NOT NULL,
    UPD_DT            TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPD_ID            VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_EXAM_ITEM PRIMARY KEY (ITEM_SEQ),
    CONSTRAINT FK_EXAM_ITEM_EXAM_ID     FOREIGN KEY (EXAM_ID)
        REFERENCES EXAM_INFO(EXAM_ID),
    CONSTRAINT FK_EXAM_ITEM_BRANCH_CODE FOREIGN KEY (BRANCH_CODE)
        REFERENCES BRANCH_INFO(BRANCH_CODE),
    CONSTRAINT FK_EXAM_ITEM_ITEM_CODE   FOREIGN KEY (ITEM_CODE)
        REFERENCES ITEM_CODE(ITEM_CODE)
);

CREATE INDEX IDX_EXAM_ITEM_COMPOSITE ON EXAM_ITEM(ITEM_CODE, PART);
